name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: "recursive"
        fetch-depth: 0

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Android Build
      run: ./dependencies/vcpkg/bootstrap-vcpkg.sh -disableMetrics && cd src/android && ./gradlew --no-daemon assembleNokeyRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: cemu.apk
        path: src/android/app/build/outputs/apk/nokeyRelease/app-nokeyRelease.apk